( DEFINE ( DOMAIN OILSPILL )
( :REQUIREMENTS :EQUALITY :NEGATIVE-PRECONDITIONS :CONDITIONAL-EFFECTS :TYPING :UNIVERSAL-PRECONDITIONS )
( :TYPES
	VEHICLE - AGENT
	TASK - OBJECT
	CAPABILITY - OBJECT
	AGENT - OBJECT
)
( :CONSTANTS
)
( :PREDICATES
	( FREE-BLOCK )
	( SELECTING )
	( APPLYING )
	( RESETTING )
	( FREE-AGENT ?AGENT0 - AGENT )
	( BUSY-AGENT ?AGENT0 - AGENT )
	( DONE-AGENT ?AGENT0 - AGENT )
	( HAS ?VEHICLE0 - VEHICLE ?CAPABILITY1 - CAPABILITY )
	( NEEDS ?TASK0 - TASK ?CAPABILITY1 - CAPABILITY )
	( AT ?VEHICLE0 - VEHICLE ?TASK1 - TASK )
	( BE_DONE_BEFORE ?TASK0 - TASK ?TASK1 - TASK )
	( DONE ?TASK0 - TASK )
	( ACTIVE-DO-TASK ?VEHICLE0 - VEHICLE ?TASK1 - TASK )
	( REQ-NEG-DO-TASK ?VEHICLE0 - VEHICLE ?TASK1 - TASK )
	( ACTIVE-MOVE-TO-TASK ?VEHICLE0 - VEHICLE ?TASK1 - TASK ?TASK2 - TASK )
	( REQ-NEG-MOVE-TO-TASK ?VEHICLE0 - VEHICLE ?TASK1 - TASK ?TASK2 - TASK )
)
( :ACTION START
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( FREE-BLOCK )
	)
  :EFFECT
	( AND
		( NOT ( FREE-BLOCK ) )
		( SELECTING )
	)
)
( :ACTION APPLY
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( SELECTING )
	)
  :EFFECT
	( AND
		( NOT ( SELECTING ) )
		( APPLYING )
	)
)
( :ACTION RESET
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( APPLYING )
	)
  :EFFECT
	( AND
		( NOT ( APPLYING ) )
		( RESETTING )
	)
)
( :ACTION FINISH
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( RESETTING )
		( FORALL
			( ?AGENT0 - AGENT )
			( FREE-AGENT ?AGENT0 )
		)
	)
  :EFFECT
	( AND
		( NOT ( RESETTING ) )
		( FREE-BLOCK )
	)
)
( :ACTION SELECT-DO-TASK
  :PARAMETERS ( ?VEHICLE0 - VEHICLE ?TASK1 - TASK )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?VEHICLE0 )
		( NOT ( REQ-NEG-DO-TASK ?VEHICLE0 ?TASK1 ) )
		( AT ?VEHICLE0 ?TASK1 )
		(FORALL (?cap - CAPABILITY)
                (imply
                    (needs ?TASK1 ?cap)
                    (has ?VEHICLE0 ?cap)
                )
            )
        (FORALL (?othertask - TASK)
            (imply
                (be_done_before ?othertask ?TASK1)
                (done ?othertask)
            )
        )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?VEHICLE0 ) )
		( BUSY-AGENT ?VEHICLE0 )
		( ACTIVE-DO-TASK ?VEHICLE0 ?TASK1 )
	)
)
( :ACTION DO-DO-TASK
  :PARAMETERS ( ?VEHICLE0 - VEHICLE ?TASK1 - TASK )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?VEHICLE0 )
		( ACTIVE-DO-TASK ?VEHICLE0 ?TASK1 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?VEHICLE0 ) )
		( DONE-AGENT ?VEHICLE0 )
		( DONE ?TASK1 )
	)
)
( :ACTION END-DO-TASK
  :PARAMETERS ( ?VEHICLE0 - VEHICLE ?TASK1 - TASK )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?VEHICLE0 )
		( ACTIVE-DO-TASK ?VEHICLE0 ?TASK1 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?VEHICLE0 ) )
		( FREE-AGENT ?VEHICLE0 )
		( NOT ( ACTIVE-DO-TASK ?VEHICLE0 ?TASK1 ) )
	)
)
( :ACTION SELECT-MOVE-TO-TASK
  :PARAMETERS ( ?VEHICLE0 - VEHICLE ?TASK1 - TASK ?TASK2 - TASK )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?VEHICLE0 )
		( NOT ( REQ-NEG-MOVE-TO-TASK ?VEHICLE0 ?TASK1 ?TASK2 ) )
		( AT ?VEHICLE0 ?TASK1 )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?VEHICLE0 ) )
		( BUSY-AGENT ?VEHICLE0 )
		( ACTIVE-MOVE-TO-TASK ?VEHICLE0 ?TASK1 ?TASK2 )
	)
)
( :ACTION DO-MOVE-TO-TASK
  :PARAMETERS ( ?VEHICLE0 - VEHICLE ?TASK1 - TASK ?TASK2 - TASK )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?VEHICLE0 )
		( ACTIVE-MOVE-TO-TASK ?VEHICLE0 ?TASK1 ?TASK2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?VEHICLE0 ) )
		( DONE-AGENT ?VEHICLE0 )
		( NOT ( AT ?VEHICLE0 ?TASK1 ) )
		( AT ?VEHICLE0 ?TASK2 )
	)
)
( :ACTION END-MOVE-TO-TASK
  :PARAMETERS ( ?VEHICLE0 - VEHICLE ?TASK1 - TASK ?TASK2 - TASK )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?VEHICLE0 )
		( ACTIVE-MOVE-TO-TASK ?VEHICLE0 ?TASK1 ?TASK2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?VEHICLE0 ) )
		( FREE-AGENT ?VEHICLE0 )
		( NOT ( ACTIVE-MOVE-TO-TASK ?VEHICLE0 ?TASK1 ?TASK2 ) )
	)
)
)
